"""Guard: MathDept.lean imports exactly the modules on disk.

The root is generated by `scripts/gen_root.py`. A new entry file that nobody
imported would compile in isolation and stay invisible to `lake build`, so the
axiom audit would never see it. This test is the thing that notices.
"""

import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def test_root_is_fresh():
    result = subprocess.run(
        [sys.executable, "scripts/gen_root.py", "--check"],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "MathDept.lean is stale. Regenerate with `python scripts/gen_root.py --write`.\n"
        + result.stdout + result.stderr
    )


def test_generated_root_carries_the_header():
    header = (REPO_ROOT / "MathDept.lean").read_text(encoding="utf-8").splitlines()[0]
    assert header == (
        "-- Generated by scripts/gen_root.py. Do not edit. "
        "Run: python scripts/gen_root.py --write"
    )
