"""`python -m mdept.view`: the consumer's generated view, and its drift guard.

The guard is the point of the command. A view that is written once and then
quietly ages is worse than no view, because a reader trusts it; `--check` is
what makes it a guard, so the cases here are mostly about what must make it
fail.
"""

import shutil
from pathlib import Path

import pytest

from mdept import CheckError, ConfigError
from mdept import family as family_mod
from mdept import view

FIXTURES = Path(__file__).resolve().parent / "fixtures"
BASES = ("good_public", "good_private")


def stage(tmp_path: Path) -> Path:
    for base in BASES:
        shutil.copytree(FIXTURES / base, tmp_path / base,
                        ignore=shutil.ignore_patterns("__pycache__"))
    return tmp_path


@pytest.fixture
def private(tmp_path):
    return stage(tmp_path) / "good_private"


def run(root: Path, *args) -> int:
    return view.main(["--consumer", "ToyRepo", "--root", str(root), *args])


# --- write, then check -----------------------------------------------------


def test_write_then_check_is_green(private, capsys):
    assert run(private, "--write") == 0
    assert run(private, "--check") == 0
    assert "is fresh" in capsys.readouterr().out


def test_check_fails_before_the_view_has_ever_been_written(private, capsys):
    """Nothing requires the view to exist: `--check` says so and fails.

    The file is generated on demand, so a consumer that has not run `--write`
    yet is in a legal state, and no other command may depend on the path being
    there.
    """
    assert not (private / "consumers/ToyRepo/docs/MATH.md").exists()
    assert run(private, "--check") == 1
    assert "does not exist" in capsys.readouterr().err


def test_a_status_change_makes_check_fail(private, capsys):
    assert run(private, "--write") == 0
    entry = private / "ledger/MD_0006.md"
    entry.write_text(entry.read_text(encoding="utf-8").replace("status: open", "status: refuted"),
                     encoding="utf-8")
    assert run(private, "--check") == 1
    assert "drifted from the ledger" in capsys.readouterr().err


def test_the_write_is_deterministic(private):
    assert run(private, "--write") == 0
    first = (private / "consumers/ToyRepo/docs/MATH.md").read_text(encoding="utf-8")
    assert run(private, "--write") == 0
    assert (private / "consumers/ToyRepo/docs/MATH.md").read_text(encoding="utf-8") == first


def test_out_writes_a_preview_somewhere_else(private, tmp_path):
    preview = tmp_path / "preview" / "MATH.md"
    assert run(private, "--write", "--out", str(preview)) == 0
    assert preview.is_file()
    assert not (private / "consumers/ToyRepo/docs/MATH.md").exists()
    assert "--consumer ToyRepo --write" in preview.read_text(encoding="utf-8"), (
        "the header names the real command, not the preview path"
    )


# --- what the file says ----------------------------------------------------


def test_the_opening_lines_declare_the_file_generated(private):
    family = family_mod.load_family(private)
    text, _path, _payload = view.generate(family, "ToyRepo")
    head = "\n".join(text.splitlines()[:8]).lower()
    assert "generated by" in head, (
        "a consumer's own generated-file scanner reads the first 8 lines for this"
    )
    assert view.HEADER_NOTE in head


def test_the_view_reports_raised_cited_and_request_tokens(private):
    family = family_mod.load_family(private)
    _text, path, payload = view.generate(family, "ToyRepo")
    assert path == private / "consumers/ToyRepo/docs/MATH.md"
    assert [record["id"] for record in payload["raised"]] == ["MD_0005", "MD_0006", "MD_0007"]
    assert [(c["id"], c["path"], c["line"]) for c in payload["cited"]] == [
        ("MD_0005", "docs/toy.md", 5),
        ("MD_0006", "docs/toy.md", 6),
        ("MD_0006", "research/toy notes.md", 4),
        ("MD_0005", "src/toy.py", 3),
    ]
    assert payload["cited"][2]["locator"] == "§2", (
        "a quoted cited_by path keeps its locator, which is the reason for quoting"
    )


def test_an_id_anchor_is_reported_with_its_line_and_its_form(private):
    family = family_mod.load_family(private)
    _text, _path, payload = view.generate(family, "ToyRepo")
    raised = {record["id"]: record for record in payload["raised"]}
    assert raised["MD_0005"]["anchor_form"] == "item"
    assert raised["MD_0005"]["anchor_line"] == 3
    assert raised["MD_0006"]["anchor_form"] == "text"


def test_an_unknown_consumer_names_the_ones_there_are(private):
    family = family_mod.load_family(private)
    with pytest.raises(ConfigError, match="the listed repos are \\['ToyRepo'\\]"):
        view.generate(family, "OtherRepo")


def test_a_cited_file_that_does_not_exist_sends_the_reader_to_check(private):
    entry = private / "ledger/MD_0005.md"
    entry.write_text(
        entry.read_text(encoding="utf-8").replace("ToyRepo:src/toy.py", "ToyRepo:src/gone.py"),
        encoding="utf-8",
    )
    family = family_mod.load_family(private)
    with pytest.raises(CheckError, match="does not exist"):
        view.generate(family, "ToyRepo")


# --- what the scan skips ---------------------------------------------------


def test_a_generated_file_and_an_ignored_tree_are_not_scanned(private):
    """Both fixture files carry an `MDR:` token that must not reach the view.

    They are the same two files I21 skips, for the same two reasons: a generated
    file mirrors an editable one, and an ignored tree is not this repo's surface.
    """
    toy = private / "consumers/ToyRepo"
    (toy / "docs/generated_notes.md").write_text(
        "# Toy generated notes\n<!-- Generated by the toy pipeline. Do not edit. -->\n\n"
        "A mirror naming MDR:2026-09-01-toy#C1 (pending).\n",
        encoding="utf-8",
    )
    (toy / "vendor/third_party.md").write_text(
        "# Vendored\n\nIt names MDR:2026-09-01-toy#C1 (pending) and is not our surface.\n",
        encoding="utf-8",
    )
    (toy / "docs/own.md").write_text(
        "# Our own note\n\nIt cites MDR:2026-09-01-toy#C1 (pending).\n", encoding="utf-8"
    )
    family = family_mod.load_family(private)
    _text, _path, payload = view.generate(family, "ToyRepo")
    assert [record["found_at"] for record in payload["requests"]] == [["docs/own.md:3"]]
    assert payload["requests"][0]["candidates"] == {"C1": "pending"}


def test_a_nested_checkout_is_another_repo_and_is_not_scanned(private):
    """An agent worktree under `.claude/` carries a copy of every citation.

    Counting it would make the same check pass or fail depending on whether
    someone is working in a worktree at that moment, which is the one thing a
    guard may not do.
    """
    tooling = private / "consumers/ToyRepo/.claude"
    checkout = tooling / "worktrees/agent-1"
    (checkout / "docs").mkdir(parents=True)
    (checkout / ".git").write_text("gitdir: elsewhere\n", encoding="utf-8")
    (checkout / "docs/own.md").write_text(
        "A copy citing MDR:2026-09-01-toy#C1 (pending).\n", encoding="utf-8"
    )
    (tooling / "settings.json").write_text("{}\n", encoding="utf-8")
    consumer = family_mod.load_family(private).consumer("ToyRepo")
    scanned = {consumer.rel(path) for path in consumer.files()}
    assert ".claude/worktrees/agent-1/docs/own.md" not in scanned
    assert ".claude/settings.json" in scanned, (
        "the rule is the nested checkout, not a blanket skip of a tooling directory"
    )


# --- a broken anchor is reported, not silently dropped ---------------------


def test_an_unresolvable_anchor_is_named_in_the_view(private):
    entry = private / "ledger/MD_0005.md"
    entry.write_text(entry.read_text(encoding="utf-8").replace("anchor: T1", "anchor: T9"),
                     encoding="utf-8")
    family = family_mod.load_family(private)
    text, _path, payload = view.generate(family, "ToyRepo")
    raised = {record["id"]: record for record in payload["raised"]}
    assert raised["MD_0005"]["anchor_condition"] == "does not resolve"
    assert "**does not resolve**" in text, (
        "the view is the file a consumer reads; a dead anchor has to be visible in it"
    )


def test_an_ambiguous_anchor_names_its_lines_in_the_view(private):
    toy = private / "consumers/ToyRepo/docs/toy.md"
    toy.write_text(toy.read_text(encoding="utf-8") + "\n## T1. The same item ID again\n",
                   encoding="utf-8")
    family = family_mod.load_family(private)
    text, _path, payload = view.generate(family, "ToyRepo")
    raised = {record["id"]: record for record in payload["raised"]}
    assert raised["MD_0005"]["anchor_condition"] == "ambiguous at lines 3, 11"
    assert "**ambiguous at lines 3, 11**" in text


def test_a_missing_document_is_named_in_the_view(private):
    (private / "consumers/ToyRepo/docs/toy.md").unlink()
    entry = private / "ledger/MD_0005.md"
    entry.write_text(
        entry.read_text(encoding="utf-8").replace('"ToyRepo:docs/toy.md §1", ', ""),
        encoding="utf-8",
    )
    other = private / "ledger/MD_0006.md"
    other.write_text(
        other.read_text(encoding="utf-8").replace('"ToyRepo:docs/toy.md §1", ', ""),
        encoding="utf-8",
    )
    family = family_mod.load_family(private)
    text, _path, payload = view.generate(family, "ToyRepo")
    raised = {record["id"]: record for record in payload["raised"]}
    assert raised["MD_0005"]["anchor_condition"] == "doc missing"
    assert "**doc missing**" in text


def test_an_entry_with_no_anchor_says_that_rather_than_nothing(private):
    family = family_mod.load_family(private)
    _text, _path, payload = view.generate(family, "ToyRepo")
    # MD_0007's raised_by carries a doc and an anchor; blank them to get the
    # shape a released entry has, where provenance is abstracted on release.
    entry = private / "ledger/MD_0007.md"
    entry.write_text(entry.read_text(encoding="utf-8").replace("anchor: T1", "anchor: null"),
                     encoding="utf-8")
    text, _path, payload = view.generate(family_mod.load_family(private), "ToyRepo")
    raised = {record["id"]: record for record in payload["raised"]}
    assert raised["MD_0007"]["anchor_condition"] == "unanchored"
    assert "not recorded: the entry carries no document anchor." in text


# --- what counts as generated, and what counts as readable -----------------


def test_the_generated_marker_has_to_open_a_line(private):
    """Prose about something "generated by hand" does not exempt a file.

    The skip is a real exemption from I21, so it has to be a declaration rather
    than a coincidence of wording. Anything a generator actually writes at the
    top of a file still counts.
    """
    consumer = family_mod.load_family(private).consumer("ToyRepo")
    path = private / "consumers/ToyRepo/docs/probe.md"
    for text, generated in [
        ("<!-- Generated by `tool` -->\n", True),
        ("> Generated by `repo-outline`\n", True),
        ("<!-- role: generated | status: current 2026-09-17 -->\n", True),
        ("**Generated by `scripts/gen.py`**\n", True),
        ("# Notes\n\nThe table below was generated by hand, so it stays.\n", False),
        ("# Notes\n\nA line about role: generated files in general.\n", False),
    ]:
        path.write_text(text, encoding="utf-8")
        assert consumer.is_generated(path) is generated, text


def test_a_file_with_no_prose_to_scan_is_skipped_and_never_crashes(private):
    """None from `text` means "nothing to scan here", for two definite reasons."""
    consumer = family_mod.load_family(private).consumer("ToyRepo")
    toy = private / "consumers/ToyRepo"
    (toy / "docs/dangling.md").symlink_to(toy / "docs/nowhere.md")
    (toy / "docs/binary.bin").write_bytes(b"\x00\xff\xfe MD_0005 \x00")
    assert consumer.text(toy / "docs/dangling.md") is None
    assert consumer.text(toy / "docs/binary.bin") is None
    assert consumer.is_generated(toy / "docs/dangling.md") is False


def test_an_unreadable_regular_file_fails_instead_of_reading_as_empty(private):
    """A permission problem reported as "no citations here" is the worst answer.

    The file is a regular file in a listed consumer, so it is a citation surface;
    being unable to read it is a finding, not a licence to skip it.
    """
    consumer = family_mod.load_family(private).consumer("ToyRepo")
    locked = private / "consumers/ToyRepo/docs/locked.md"
    locked.write_text("It cites MD_0005 (open).\n", encoding="utf-8")
    locked.chmod(0o000)
    try:
        with pytest.raises(CheckError, match="cannot be read"):
            consumer.text(locked)
    finally:
        locked.chmod(0o644)


def test_a_mistyped_request_token_names_the_line_that_holds_it(private):
    own = private / "consumers/ToyRepo/docs/own.md"
    own.write_text("# Note\n\nIt cites MDR:2026-09-01-toyy#C1 (pending).\n", encoding="utf-8")
    family = family_mod.load_family(private)
    with pytest.raises(CheckError, match=r"ToyRepo:docs/own\.md:3"):
        view.generate(family, "ToyRepo")


def test_a_request_token_naming_a_candidate_that_does_not_exist_is_located(private):
    own = private / "consumers/ToyRepo/docs/own.md"
    own.write_text("# Note\n\nIt cites MDR:2026-09-01-toy#C9 (pending).\n", encoding="utf-8")
    family = family_mod.load_family(private)
    with pytest.raises(CheckError, match=r"ToyRepo:docs/own\.md:3.*C9"):
        view.generate(family, "ToyRepo")
