"""Guard: docs/MAP.md stays in sync with the source.

The map is generated by `repo-outline` (in the universal-tools repo). This test
fails if a symbol was added or moved without refreshing the map (`repo-outline
--write`). It skips when the tool is not on PATH — e.g. public CI — so it only
enforces freshness in an environment that has the family tooling.
"""
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent


def test_map_is_fresh():
    if shutil.which("repo-outline") is None:
        pytest.skip("repo-outline not on PATH (universal-tools); map freshness guard skipped")
    result = subprocess.run(
        ["repo-outline", "--check"],
        cwd=REPO_ROOT, capture_output=True, text=True,
    )
    assert result.returncode == 0, (
        "docs/MAP.md is stale — regenerate with `repo-outline --write`.\n"
        + result.stdout + result.stderr
    )
