"""Ledger invariants I1 to I21.

Run: `python -m mdept.check [--root PATH] [--run-counterexamples] [--family] [--lean]`

Every invariant raises `CheckError` on the first violation it finds, naming the
invariant, the offending path, and the offending field. There is no warnings
tier and no partial pass: I9b is the single informational check, and it is
reported as a notice that also lands in `ledger/INDEX.md` section 7.

Modes:

- plain, the default: everything that needs only this repo's markdown.
- `--run-counterexamples`: additionally executes each counterexample artifact
  and requires its witness to verify.
- `--family`: additionally resolves sibling repos through `repos.yaml`. A repo
  listed there and absent from disk fails; it never skips.
- `--lean`: additionally reads `audit/latest.json` and checks formal pointers,
  axioms, and statement hashes against it. A stale audit fails.

Two scoping decisions worth knowing before reading the code:

- I12 scans the surfaces that make claims about entries (the ledger, proofs,
  counterexample notes, the bibliography, and on the private side triage,
  inbox and sources). It does not scan instructional prose (`docs/`, `README.md`,
  `CLAUDE.md`, the skills), where an ID like MD_0007 is an illustration, nor the
  templates, whose placeholder IDs are the point. I21 is the mirror of it
  pointed outward: it scans a listed consumer's own files, where an ID is a
  reliance rather than an illustration.
- HTML comments are stripped before any token scan, which is what makes a
  commented-out example in `bibliography.md` legal.
"""

from __future__ import annotations

import argparse
import sys
from dataclasses import dataclass, field
from pathlib import Path

from . import CheckError, ConfigError
from . import anchors
from . import audit as audit_mod
from . import config, parse, schema
from . import family as family_mod

#: Surfaces I12 scans for MD_#### and MDR: tokens.
REFERENCE_SURFACES = (
    "ledger",
    "proofs",
    "counterexamples",
    "bibliography.md",
    "triage",
    "inbox",
    "sources",
)

#: Markdown outside the em-dash sweep. `tests/fixtures` carries a deliberate
#: violation as a test case, and `docs/MAP.md` is emitted by `repo-outline`,
#: which uses em dashes as its own separator; its prose is docstrings already
#: swept at the source, which is the only place anyone can fix one.
EM_DASH_EXCLUDE = ("tests/fixtures", "docs/MAP.md")

#: Docs whose line 2 must be a role line. `docs/MAP.md` is generated by a tool
#: that owns its own header.
ROLE_LINE_SURFACES = ("docs", "proofs", "triage")

STANDARD_AXIOMS = ("propext", "Classical.choice", "Quot.sound")


def fail(invariant: str, path, field_name: str, message: str) -> None:
    raise CheckError(f"{invariant}: {path}: field '{field_name}': {message}")


@dataclass
class Context:
    root: Path
    kind: str
    entries: list
    by_id: dict
    bibliography: dict
    requests: list
    run_counterexamples: bool
    family: bool
    lean: bool
    consumers: dict | None = None
    sibling: Path | None = None
    audit: dict | None = None
    notices: list = field(default_factory=list)
    _sibling_entries: list | None = field(default=None, repr=False)

    @property
    def private(self) -> bool:
        return self.kind == "private"

    def rel(self, path) -> str:
        try:
            return str(Path(path).resolve().relative_to(self.root))
        except ValueError:
            return str(path)

    def family_by_id(self) -> dict:
        """Both ledgers' entries by ID: an ID resolves wherever it lives.

        Releasing an entry moves it to the public repo, so a consumer's citation
        of a released ID is checked against the public entry while the private
        repo is the one running the family check.
        """
        if self._sibling_entries is None:
            sibling = self.sibling if self.sibling is not None else config.public_root(self.root)
            self._sibling_entries = (
                parse.load_entries(sibling)
                if sibling is not None and sibling != self.root and (sibling / "ledger").is_dir()
                else []
            )
        return {e.id: e for e in [*self._sibling_entries, *self.entries]}


# --- I1 filename = id -------------------------------------------------------


def i1_filename_is_id(ctx: Context) -> None:
    for entry in ctx.entries:
        if entry.front.get("id") != entry.path.stem:
            fail("I1 filename", ctx.rel(entry.path), "id",
                 f"front matter says {entry.front.get('id')!r}, the filename says {entry.path.stem!r}")


def _precheck_filenames(root: Path) -> None:
    for path in parse.entry_paths(root):
        if not schema.ID_RE.match(path.stem):
            fail("I1 filename", path.name, "<filename>",
                 "a ledger entry filename is MD_ plus four digits, for example MD_0007.md")


# --- I2 permanence ----------------------------------------------------------


def i2_permanence(ctx: Context) -> None:
    seen: dict[str, Path] = {}
    for entry in ctx.entries:
        if entry.id in seen:
            fail("I2 permanence", ctx.rel(entry.path), "id",
                 f"{entry.id} is already used by {ctx.rel(seen[entry.id])}; IDs are never reused")
        seen[entry.id] = entry.path
    if not ctx.family:
        return
    union = dict(seen)
    if ctx.sibling is not None:
        for entry in parse.load_entries(ctx.sibling):
            if entry.id in union:
                fail("I2 permanence", ctx.rel(union[entry.id]), "id",
                     f"{entry.id} also exists in the sibling repo at {entry.path}; "
                     "IDs are allocated across both repos")
            union[entry.id] = entry.path
    if not union:
        return
    numbers = sorted(int(mid.split("_")[1]) for mid in union)
    expected = list(range(1, len(numbers) + 1))
    if numbers != expected:
        missing = sorted(set(expected) - set(numbers))
        fail("I2 permanence", ctx.rel(ctx.root), "<union>",
             f"the union of both repos must be MD_0001..MD_{len(numbers):04d} with no gap; "
             f"missing {['MD_%04d' % n for n in missing]}")


# --- I3 schema --------------------------------------------------------------


def i3_schema(ctx: Context) -> None:
    for entry in ctx.entries:
        schema.validate_front(entry.front, ctx.rel(entry.path), ctx.kind)
        headings = list(entry.sections())
        for required in schema.BODY_HEADINGS:
            if required not in headings:
                fail("I3 schema", ctx.rel(entry.path), "<body>",
                     f"missing the '## {required}' section; the four sections are {list(schema.BODY_HEADINGS)}")


# --- I4 status and evidence -------------------------------------------------


def i4_status_evidence(ctx: Context) -> None:
    for entry in ctx.entries:
        status = entry.status
        settled = entry.at("provenance.settled_by")
        evidence = entry.front["evidence"]
        by_kind: dict[str, list[str]] = {}
        for i, item in enumerate(evidence):
            target = ctx.root / item["path"]
            if not target.exists():
                fail("I4 status/evidence", ctx.rel(entry.path), f"evidence[{i}].path",
                     f"{item['path']} does not exist in this repo")
            by_kind.setdefault(item["kind"], []).append(item["path"])

        if status in schema.UNSETTLED_STATUSES:
            if settled is not None:
                fail("I4 status/evidence", ctx.rel(entry.path), "provenance.settled_by",
                     f"status {status!r} is unsettled, so settled_by must be null")
        elif settled is None:
            fail("I4 status/evidence", ctx.rel(entry.path), "provenance.settled_by",
                 f"status {status!r} is settled, so settled_by is required")

        if status == "cited":
            if entry.front["source"] is None:
                fail("I4 status/evidence", ctx.rel(entry.path), "source",
                     "a cited entry names the bibliography tag it rests on")
            _require_how(ctx, entry, settled, "citation")
        elif status == "proven-formal":
            if entry.at("formal.decl") is None:
                fail("I4 status/evidence", ctx.rel(entry.path), "formal.decl",
                     "a proven-formal entry points at the Lean declaration that proves it")
            _require_how(ctx, entry, settled, "lean")
        elif status == "proven-informal":
            expected = f"proofs/{entry.id}.md"
            if expected not in by_kind.get("proof", []):
                fail("I4 status/evidence", ctx.rel(entry.path), "evidence",
                     f"a proven-informal entry carries evidence {{kind: proof, path: {expected}}}")
            proof_text = (ctx.root / expected).read_text(encoding="utf-8")
            if "Formalization blockers" not in proof_text:
                fail("I4 status/evidence", expected, "<body>",
                     "an informal proof states what blocks its formalization "
                     "under a 'Formalization blockers' heading")
            _require_how(ctx, entry, settled, "informal-proof")
            if settled.get("checked_by") is None:
                fail("I4 status/evidence", ctx.rel(entry.path), "provenance.settled_by.checked_by",
                     "an informal proof is only proven once a second session has checked it")
        elif status == "refuted":
            if not by_kind.get("counterexample"):
                fail("I4 status/evidence", ctx.rel(entry.path), "evidence",
                     "a refuted entry carries evidence {kind: counterexample, path: counterexamples/...}")
            _require_how(ctx, entry, settled, "counterexample")
        elif status == "merged":
            if entry.front["merged_into"] is None:
                fail("I4 status/evidence", ctx.rel(entry.path), "merged_into",
                     "a merged entry names the entry it merged into")


def _require_how(ctx: Context, entry, settled, how: str) -> None:
    if settled.get("how") != how:
        fail("I4 status/evidence", ctx.rel(entry.path), "provenance.settled_by.how",
             f"status {entry.status!r} requires how {how!r}, found {settled.get('how')!r}")


# --- I5 formal pointer ------------------------------------------------------


def i5_formal_pointer(ctx: Context) -> None:
    if not ctx.lean:
        return
    data = ctx.audit
    declarations = data.get("declarations") or {}
    fresh = audit_mod.sources_sha256(ctx.root)
    if data.get("sources_sha256") != fresh:
        fail("I5 formal pointer", "audit/latest.json", "sources_sha256",
             "the cached audit is stale against the Lean sources on disk; run `make lean`")
    allowlist = audit_mod.read_allowlist(ctx.root)
    for entry in ctx.entries:
        decl = entry.at("formal.decl")
        if decl is None:
            continue
        lean_file = ctx.root / entry.at("formal.file")
        if not lean_file.is_file():
            fail("I5 formal pointer", ctx.rel(entry.path), "formal.file",
                 f"{entry.at('formal.file')} does not exist")
        record = declarations.get(decl)
        if record is None:
            fail("I5 formal pointer", ctx.rel(entry.path), "formal.decl",
                 f"{decl} is not in audit/latest.json; it did not compile or was renamed")
        if entry.status == "proven-formal" and ".Results." not in record["module"]:
            fail("I5 formal pointer", ctx.rel(entry.path), "formal.decl",
                 f"{decl} lives in module {record['module']}; a proven entry lives under Results/")
        permitted = set(STANDARD_AXIOMS) | {a for d, a in allowlist if d == decl}
        offending = sorted(set(record.get("axioms") or []) - permitted)
        if offending:
            fail("I5 formal pointer", ctx.rel(entry.path), "formal.decl",
                 f"{decl} depends on {offending}; add a line to audit/axiom-allowlist.txt "
                 "only with an explicit reason")
        expected_hash = audit_mod.type_hash(record["type"])
        if entry.front["statement_hash"] != expected_hash:
            fail("I5 formal pointer", ctx.rel(entry.path), "statement_hash",
                 f"the frozen statement hash does not match the compiled type of {decl}; "
                 "a changed statement is a new entry with `revises`, never an edit")


# --- I6 counterexample artifacts --------------------------------------------


def i6_counterexamples(ctx: Context) -> None:
    claimed: set[Path] = set()
    for entry in ctx.entries:
        for item in entry.front["evidence"]:
            if item["kind"] != "counterexample":
                continue
            target = ctx.root / item["path"]
            claimed.add(target.resolve())
            if target.suffix != ".py":
                fail("I6 counterexample", ctx.rel(entry.path), "evidence.path",
                     f"{item['path']} is not a Python artifact")
            if not schema.COUNTEREXAMPLE_STEM_RE.match(target.stem):
                fail("I6 counterexample", item["path"], "<filename>",
                     "a counterexample filename is MD_####_slug.py with a lower-case slug")
            if not target.stem.startswith(entry.id + "_"):
                fail("I6 counterexample", ctx.rel(entry.path), "evidence.path",
                     f"{item['path']} does not belong to {entry.id}")
            source = target.read_text(encoding="utf-8")
            if "def refute(" not in source:
                fail("I6 counterexample", item["path"], "refute",
                     "a counterexample artifact defines `def refute() -> Witness`")
            if ctx.run_counterexamples:
                from . import refute as refute_mod

                witness = refute_mod.load(target)
                if witness.entry != entry.id:
                    fail("I6 counterexample", item["path"], "Witness.entry",
                         f"the witness names {witness.entry!r}, the artifact belongs to {entry.id}")
                if not witness.verify():
                    fail("I6 counterexample", item["path"], "Witness.verify",
                         "the claim did not evaluate to False at the witness point")
    directory = ctx.root / "counterexamples"
    if directory.is_dir():
        for path in sorted(directory.glob("*.py")):
            if path.name.startswith("_"):
                continue
            if path.resolve() not in claimed:
                fail("I6 counterexample", ctx.rel(path), "<orphan>",
                     "no ledger entry lists this artifact as evidence")


# --- I7 raised-by resolves --------------------------------------------------


def i7_raised_by(ctx: Context) -> None:
    """Every anchor is a form of the grammar, and resolves to one place.

    An entry's `provenance.raised_by` and a request's `from` both point into a
    consumer document, so both are resolved here. `mdept.anchors` owns the
    grammar; this invariant owns what a failure to resolve means.
    """
    if not (ctx.family and ctx.private):
        return
    for entry in ctx.entries:
        _check_anchor(ctx, ctx.rel(entry.path), "provenance.raised_by",
                      entry.at("provenance.raised_by"))
    for request in ctx.requests:
        _check_anchor(ctx, request.rel, "from", request.front.get("from"))
    from . import index as index_mod

    ctx.notices.extend(index_mod.anchor_notices(ctx.entries, ctx.requests))


def _check_anchor(ctx: Context, where: str, field_name: str, source) -> None:
    if source is None:
        return
    repo = source.get("repo")
    if repo not in ctx.consumers:
        fail("I7 raised-by", where, f"{field_name}.repo",
             f"{repo!r} is not a key of repos.yaml consumers {sorted(ctx.consumers)}")
    doc = source.get("doc")
    if doc is None:
        return
    consumer = ctx.consumers[repo]
    doc_path = _consumer_path(ctx, repo) / doc
    if not doc_path.is_file():
        fail("I7 raised-by", where, f"{field_name}.doc", f"{doc_path} does not exist")
    anchor = source.get("anchor")
    if anchor is None:
        return
    form = anchors.classify(anchor)
    if form == "unknown":
        fail("I7 raised-by", where, f"{field_name}.anchor",
             f"{anchor!r} is no form of the anchor grammar: {anchors.GRAMMAR}")
    text = consumer.text(doc_path)
    if text is None:
        fail("I7 raised-by", where, f"{field_name}.doc",
             f"{doc_path} is not a text file, so no anchor can resolve in it")
    found = anchors.matches(anchor, text)
    if not found:
        fail("I7 raised-by", where, f"{field_name}.anchor",
             f"{anchor!r} (form {form}) resolves nowhere in {doc_path}")
    if form in anchors.UNIQUE_FORMS and len(found) > 1:
        fail("I7 raised-by", where, f"{field_name}.anchor",
             f"{anchor!r} (form {form}) resolves at lines {[hit.line for hit in found]} "
             f"of {doc_path}; an anchor names one place")


def _consumer_path(ctx: Context, repo: str, invariant: str = "I7 raised-by") -> Path:
    path = ctx.consumers[repo].path
    if not path.is_dir():
        fail(invariant, "repos.yaml", f"consumers.{repo}",
             f"{path} is listed but absent from disk; a listed repo is required, never skipped")
    return path


# --- I8 links resolve -------------------------------------------------------


def i8_links(ctx: Context) -> None:
    for entry in ctx.entries:
        for field_name, targets in entry.linked_ids().items():
            for target in targets:
                if target == entry.id:
                    fail("I8 links", ctx.rel(entry.path), field_name, f"{target} links to itself")
                other = ctx.by_id.get(target)
                if other is None:
                    fail("I8 links", ctx.rel(entry.path), field_name, f"{target} does not exist")
                if other.status == "merged" and field_name != "merged_into":
                    fail("I8 links", ctx.rel(entry.path), field_name,
                         f"{target} is merged into {other.front['merged_into']}; link to that instead")
        merged_into = entry.front["merged_into"]
        if merged_into is not None and ctx.by_id[merged_into].status == "merged":
            fail("I8 links", ctx.rel(entry.path), "merged_into",
                 f"{merged_into} is itself merged; merged_into resolves to a live entry")


# --- I9 contradiction and inheritance ---------------------------------------

_IMPLIED_BY = ("below_of", "special_case_of")
_IMPLIES = ("above_of", "generalizes")
_ESTABLISHED = ("cited", "proven-formal", "proven-informal")


def i9a_no_contradiction(ctx: Context) -> None:
    for entry in ctx.entries:
        between = entry.front["between"]
        if entry.status == "refuted":
            for relation in _IMPLIED_BY:
                for target in between[relation]:
                    other = ctx.by_id[target]
                    if other.status in _ESTABLISHED:
                        fail("I9a contradiction", ctx.rel(entry.path), f"between.{relation}",
                             f"{entry.id} is refuted but {target} ({other.status}) implies it; "
                             "one of the two is wrong")
        if entry.status in _ESTABLISHED:
            for relation in _IMPLIES:
                for target in between[relation]:
                    other = ctx.by_id[target]
                    if other.status == "refuted":
                        fail("I9a contradiction", ctx.rel(entry.path), f"between.{relation}",
                             f"{entry.id} ({entry.status}) implies {target}, which is refuted; "
                             "one of the two is wrong")


def i9b_inheritance_notice(ctx: Context) -> None:
    """The one informational check. Its notices are section 7 of the generated index."""
    from . import index as index_mod

    ctx.notices.extend(index_mod.inheritance_notices(ctx.entries))


# --- I10 cited sources ------------------------------------------------------


def i10_cited_sources(ctx: Context) -> None:
    for entry in ctx.entries:
        source = entry.front["source"]
        if source is None:
            continue
        tag = schema.BIB_TAG_RE.match(source).group(1)
        bib = ctx.bibliography.get(tag)
        if bib is None:
            fail("I10 cited source", ctx.rel(entry.path), "source",
                 f"[{tag}] has no entry in bibliography.md")
        kind = bib.source_kind
        if kind not in schema.SOURCE_KINDS:
            fail("I10 cited source", "bibliography.md", f"[{tag}].Kind",
                 f"{kind!r} is not one of {list(schema.SOURCE_KINDS)}")
        if entry.status == "cited" and kind not in schema.TRUSTED_SOURCE_KINDS:
            fail("I10 cited source", ctx.rel(entry.path), "source",
                 f"[{tag}] is Kind {kind!r}; a cited entry rests only on {list(schema.TRUSTED_SOURCE_KINDS)}")
        if ctx.private:
            extract = ctx.root / "sources" / f"{tag}_extract.md"
            if not extract.is_file():
                fail("I10 cited source", ctx.rel(entry.path), "source",
                     f"[{tag}] has no extract at sources/{tag}_extract.md")


# --- I11 tag and extract sync -----------------------------------------------


def i11_tag_sync(ctx: Context) -> None:
    if not ctx.private:
        return
    sources = ctx.root / "sources"
    on_disk = {p.stem[: -len("_extract")] for p in sources.glob("*_extract.md")} if sources.is_dir() else set()
    for tag in sorted(ctx.bibliography):
        if tag not in on_disk:
            fail("I11 tag sync", "bibliography.md", f"[{tag}]",
                 f"no extract at sources/{tag}_extract.md")
    for tag in sorted(on_disk):
        if tag not in ctx.bibliography:
            fail("I11 tag sync", f"sources/{tag}_extract.md", "<tag>",
                 f"no bibliography entry '### [{tag}]'")
        text = (sources / f"{tag}_extract.md").read_text(encoding="utf-8")
        if f"**Bibliography tag:** [{tag}]" not in text:
            fail("I11 tag sync", f"sources/{tag}_extract.md", "Bibliography tag",
                 f"the extract does not declare '**Bibliography tag:** [{tag}]'")


# --- I12 no dangling references ---------------------------------------------


def i12_dangling_references(ctx: Context) -> None:
    for path in _reference_surfaces(ctx):
        text = path.read_text(encoding="utf-8")
        for token in sorted(parse.id_tokens(text)):
            if token not in ctx.by_id and not _known_in_sibling(ctx, token):
                fail("I12 dangling", ctx.rel(path), "<MD token>",
                     f"{token} does not resolve to a ledger entry")
        if not ctx.private:
            continue
        stems = {r.stem: r for r in ctx.requests}
        for stem, candidate in sorted(parse.request_tokens(text)):
            request = stems.get(stem)
            if request is None:
                fail("I12 dangling", ctx.rel(path), "<MDR token>",
                     f"MDR:{stem}#{candidate} names no request in inbox/ or inbox/done/")
            if candidate not in request.candidates():
                fail("I12 dangling", ctx.rel(path), "<MDR token>",
                     f"{request.rel} has no '### {candidate}' heading")


def _reference_surfaces(ctx: Context) -> list[Path]:
    paths: list[Path] = []
    for surface in REFERENCE_SURFACES:
        target = ctx.root / surface
        if target.is_file() and target.suffix == ".md":
            paths.append(target)
        elif target.is_dir():
            paths.extend(parse.iter_markdown(target))
    return [p for p in sorted(set(paths)) if p.name not in ("TEMPLATE.md", "INDEX.md")]


def _known_in_sibling(ctx: Context, token: str) -> bool:
    """True when a private repo's token names an entry that lives in the public one.

    Releasing an entry moves it out of this repo but deliberately leaves its
    triage record behind, because attempts stay private. That record still names
    the ID, so a private repo resolves unknown tokens against its public sibling
    even outside `--family`. The public repo never does the reverse: it has to
    validate standalone in CI, where no private repo exists.
    """
    if not ctx.private:
        return False
    return token in ctx.family_by_id()


# --- I13 inbox lifecycle ----------------------------------------------------


def i13_inbox(ctx: Context) -> None:
    if not ctx.private:
        return
    for request in ctx.requests:
        if not schema.REQUEST_STEM_RE.match(request.stem):
            fail("I13 inbox", request.rel, "<filename>",
                 "a request filename is YYYY-MM-DD-slug.md with a lower-case hyphenated slug")
        if request.front.get("request") != request.stem:
            fail("I13 inbox", request.rel, "request",
                 f"front matter says {request.front.get('request')!r}, the filename stem is {request.stem!r}")
        state = request.state
        if request.closed and state != "closed":
            fail("I13 inbox", request.rel, "state",
                 f"a request in inbox/done/ is state 'closed', found {state!r}")
        if not request.closed and state not in ("new", "triaged"):
            fail("I13 inbox", request.rel, "state",
                 f"a request in inbox/ is state 'new' or 'triaged', found {state!r}")
        if not request.candidates():
            fail("I13 inbox", request.rel, "<body>", "a request offers at least one '### C1' candidate")
        if not request.closed:
            continue
        outcome = request.outcome()
        if not outcome.strip():
            fail("I13 inbox", request.rel, "Outcome", "a closed request carries an Outcome block")
        for candidate in request.candidates():
            line = request.outcome_line(candidate)
            if line is None:
                fail("I13 inbox", request.rel, "Outcome",
                     f"{candidate} has no line in the Outcome block")
            if not (schema.ID_TOKEN_RE.search(line) or "declined:" in line):
                fail("I13 inbox", request.rel, "Outcome",
                     f"{candidate} maps to neither an MD_#### id nor 'declined: <reason>'")


# --- I14 request back-links -------------------------------------------------


def i14_request_backlinks(ctx: Context) -> None:
    if not ctx.private:
        return
    stems = {r.stem: r for r in ctx.requests}
    for entry in ctx.entries:
        token = entry.at("provenance.stipulated_by.request")
        if token is None:
            continue
        stem, candidate = schema.REQUEST_TOKEN_RE.fullmatch(token).groups()
        request = stems.get(stem)
        if request is None:
            fail("I14 back-link", ctx.rel(entry.path), "provenance.stipulated_by.request",
                 f"{token} names no request in inbox/ or inbox/done/")
        if candidate not in request.candidates():
            fail("I14 back-link", ctx.rel(entry.path), "provenance.stipulated_by.request",
                 f"{request.rel} has no '### {candidate}' heading")
        if request.closed and entry.id not in parse.id_tokens(request.outcome()):
            fail("I14 back-link", request.rel, "Outcome",
                 f"{entry.id} cites this request but the Outcome does not name it")
    for request in ctx.requests:
        for token in sorted(parse.id_tokens(request.outcome())):
            entry = ctx.by_id.get(token)
            if entry is None:
                fail("I14 back-link", request.rel, "Outcome", f"{token} does not exist")
            back = entry.at("provenance.stipulated_by.request")
            if back is None or not back.startswith(f"MDR:{request.stem}#"):
                fail("I14 back-link", ctx.rel(entry.path), "provenance.stipulated_by.request",
                     f"{request.rel} claims {token}, but the entry points at {back!r}")


# --- I15 consumer citations -------------------------------------------------


def i15_consumer_citations(ctx: Context) -> None:
    """Every line of a listed file that names an entry carries its status word.

    `cited_by` may name any text file the consumer owns, code included: a
    comment or a docstring that leans on an unsettled statement is a citation,
    and a line is a line wherever it sits. The status word is what makes the
    reliance readable where it is written, without a trip to the ledger.
    """
    if not ctx.family:
        return
    for entry in ctx.entries:
        for i, citation in enumerate(entry.front["cited_by"]):
            repo, rel, _locator = schema.split_cited_by(citation)
            if repo not in ctx.consumers:
                fail("I15 citation", ctx.rel(entry.path), f"cited_by[{i}]",
                     f"{repo!r} is not a key of repos.yaml consumers {sorted(ctx.consumers)}")
            consumer = ctx.consumers[repo]
            doc = _consumer_path(ctx, repo, "I15 citation") / rel
            if not doc.is_file():
                fail("I15 citation", ctx.rel(entry.path), f"cited_by[{i}]", f"{doc} does not exist")
            text = consumer.text(doc)
            if text is None:
                fail("I15 citation", ctx.rel(entry.path), f"cited_by[{i}]",
                     f"{doc} is not a text file, so it carries no citation line")
            lines = [(n, l) for n, l in enumerate(text.splitlines(), start=1) if entry.id in l]
            if not lines:
                fail("I15 citation", ctx.rel(entry.path), f"cited_by[{i}]",
                     f"{doc} does not mention {entry.id}")
            required = schema.citation_words(entry.status)
            if not required:
                continue
            for number, line in lines:
                if not any(word in line.lower() for word in required):
                    fail("I15 citation", f"{repo}:{rel}:{number}", "<line>",
                         f"cites {entry.id} without any of {list(required)}; "
                         f"the entry is {entry.status}")


# --- I16 generated views fresh ----------------------------------------------


def i16_generated_views(ctx: Context) -> None:
    from . import index as index_mod

    for rel, rendered in index_mod.render(ctx.root).items():
        path = ctx.root / rel
        if not path.is_file():
            fail("I16 generated", rel, "<file>", "the generated view is missing; run `make regen`")
        if path.read_text(encoding="utf-8") != rendered:
            fail("I16 generated", rel, "<content>",
                 "the generated view drifted from the ledger; run `make regen`")


# --- I17 prose --------------------------------------------------------------


def i17_prose(ctx: Context) -> None:
    for path in parse.iter_markdown(ctx.root, exclude=EM_DASH_EXCLUDE):
        text = path.read_text(encoding="utf-8")
        for number, line in enumerate(text.splitlines(), start=1):
            if schema.EM_DASH in line:
                fail("I17 prose", f"{ctx.rel(path)}:{number}", "<em dash>",
                     "an em dash (U+2014) is never house style; use a period, a comma, a colon, or parentheses")


# --- I18 dates --------------------------------------------------------------


def i18_dates(ctx: Context) -> None:
    for entry in ctx.entries:
        stipulated = entry.at("provenance.stipulated_by.date")
        settled = entry.at("provenance.settled_by")
        if settled is None or stipulated is None:
            continue
        if settled["date"] < stipulated:
            fail("I18 dates", ctx.rel(entry.path), "provenance.settled_by.date",
                 f"settled {settled['date']} precedes stipulated {stipulated}")
        checked_by = settled.get("checked_by")
        if checked_by is not None and checked_by <= settled["date"]:
            fail("I18 dates", ctx.rel(entry.path), "provenance.settled_by.checked_by",
                 f"{checked_by} is not strictly after {settled['date']}; "
                 "the check is a second session, on a later day")


# --- I19 attempt records and role lines -------------------------------------


def i19_attempt_records(ctx: Context) -> None:
    for surface in ROLE_LINE_SURFACES:
        directory = ctx.root / surface
        if not directory.is_dir():
            continue
        for path in parse.iter_markdown(directory):
            if path.name in ("MAP.md", "TEMPLATE.md", "INDEX.md"):
                continue
            parse.parse_role_line(path)
    if not ctx.private:
        return
    for entry in ctx.entries:
        needs_record = entry.status == "open" or (
            entry.at("provenance.settled_by") is not None
            and entry.at("provenance.settled_by.how") != "citation"
        )
        if not needs_record:
            continue
        record = ctx.root / "triage" / f"{entry.id}.md"
        if not record.is_file():
            fail("I19 attempt record", ctx.rel(entry.path), "<triage>",
                 f"status {entry.status!r} requires an attempt record at triage/{entry.id}.md")
        role, _ = parse.parse_role_line(record)
        if role != "record":
            fail("I19 attempt record", f"triage/{entry.id}.md", "<role line>",
                 f"role is {role!r}; a triage record carries role 'record'")


# --- I20 sorry fence --------------------------------------------------------


def i20_sorry_fence(ctx: Context) -> None:
    violations = audit_mod.sorry_violations(ctx.root)
    if violations:
        first = violations[0]
        fail("I20 sorry fence", first["file"], "sorry",
             f"line {first['line']}: {first['reason']}")


# --- I21 no unlisted consumer citation --------------------------------------


def i21_unlisted_citations(ctx: Context) -> None:
    """Every entry mention in a listed consumer appears in that entry's `cited_by`.

    I15 checks the citations the ledger knows about. This checks the other
    direction, which is the one that rots: a consumer adds a reliance and the
    ledger never hears, so a refutation reaches every document but that one.
    Three things are skipped, each for a reason that is not "it is noisy":
    a file that declares itself generated is a mirror whose source is the
    editable surface, the consumer's own generated view is this package's
    output, and an `ignore` glob is the consumer's own declaration that a tree
    (build output, vendored code, fleet results) is not a citation surface.
    """
    if not ctx.family:
        return
    cited = {}
    for entry in ctx.family_by_id().values():
        pairs = set()
        for citation in entry.front["cited_by"]:
            split = schema.split_cited_by(citation)
            if split is not None:
                pairs.add((split[0], split[1]))
        cited[entry.id] = pairs
    for name in sorted(ctx.consumers):
        consumer = ctx.consumers[name]
        _consumer_path(ctx, name, "I21 unlisted citation")
        view = consumer.view_path
        for path in consumer.files():
            if path == view:
                continue
            text = consumer.text(path)
            if text is None or consumer.is_generated(path, text):
                continue
            rel = consumer.rel(path)
            for token in sorted(parse.id_tokens(text)):
                if token not in cited:
                    fail("I21 unlisted citation", f"{name}:{rel}", "<MD token>",
                         f"{token} resolves to no entry in either ledger")
                if (name, rel) not in cited[token]:
                    fail("I21 unlisted citation", f"{name}:{rel}", "<MD token>",
                         f"{token} is relied on here but its cited_by does not list "
                         f"'{schema.cited_by_form(name, rel)}'; add it, or the next "
                         "status change misses this file")


INVARIANTS = (
    i1_filename_is_id,
    i2_permanence,
    i3_schema,
    i4_status_evidence,
    i5_formal_pointer,
    i6_counterexamples,
    i7_raised_by,
    i8_links,
    i9a_no_contradiction,
    i9b_inheritance_notice,
    i10_cited_sources,
    i11_tag_sync,
    i12_dangling_references,
    i13_inbox,
    i14_request_backlinks,
    i15_consumer_citations,
    i16_generated_views,
    i17_prose,
    i18_dates,
    i19_attempt_records,
    i20_sorry_fence,
    i21_unlisted_citations,
)


def bibliography_path(root: Path, kind: str) -> Path:
    """The bibliography this repo checks against.

    There is one bibliography and it lives in the public repo, because citations
    are public even while the reading behind them is not. A private repo with no
    local copy therefore resolves the public sibling's, which is what makes the
    tag-to-extract sync (I11) meaningful across the pair.
    """
    local = Path(root) / "bibliography.md"
    if local.is_file() or kind == "public":
        return local
    sibling = config.public_root(root)
    if sibling is None:
        raise ConfigError(
            f"{root} has no bibliography.md and no public sibling to read one from. "
            "Set repos.yaml public_sibling, or MATHDEPT_PUBLIC."
        )
    return sibling / "bibliography.md"


def build_context(root: Path, run_counterexamples: bool, family: bool, lean: bool) -> Context:
    root = Path(root).resolve()
    _precheck_filenames(root)
    located = family_mod.locate(root)
    repo = located.repo_at(root)
    entries = repo.entries()
    kind = repo.kind
    bibliography = parse.parse_bibliography(bibliography_path(root, kind))
    ctx = Context(
        root=root,
        kind=kind,
        entries=entries,
        by_id={e.front.get("id"): e for e in entries},
        bibliography=bibliography,
        requests=repo.requests(),
        run_counterexamples=run_counterexamples,
        family=family,
        lean=lean,
    )
    if family:
        repos_yaml = root / "repos.yaml"
        if not repos_yaml.is_file():
            raise ConfigError(
                f"--family needs {repos_yaml}, which maps consumer names to paths. "
                "It lives in the private repo; run --family from a session there."
            )
        ctx.consumers = located.consumers
        ctx.sibling = located.sibling_of(root)
        # Eagerly, not lazily: the design's rule is that a repo listed in
        # repos.yaml and absent from disk FAILS. Resolving only the repos some
        # entry happens to name would let a stale path sit unnoticed until the
        # first entry that needs it, which is the wrong time to find out.
        for consumer in sorted(ctx.consumers):
            _consumer_path(ctx, consumer)
    if lean:
        cached = root / "audit" / "latest.json"
        if not cached.is_file():
            raise ConfigError(f"--lean needs {cached}; generate it with `make lean`")
        ctx.audit = audit_mod.read_cached_audit(root)
    return ctx


def run(root: Path | str | None = None,
        run_counterexamples: bool = False,
        family: bool = False,
        lean: bool = False) -> Context:
    """Run every invariant in order. Raises `CheckError` on the first violation."""
    resolved = config.find_repo_root(root) if root is None else Path(root).resolve()
    ctx = build_context(resolved, run_counterexamples, family, lean)
    for invariant in INVARIANTS:
        invariant(ctx)
    return ctx


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m mdept.check", description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=None, help="repo root (default: nearest ancestor with ledger/)")
    parser.add_argument("--run-counterexamples", action="store_true",
                        help="execute every counterexample artifact and require its witness to verify")
    parser.add_argument("--family", action="store_true",
                        help="resolve sibling and consumer repos through repos.yaml")
    parser.add_argument("--lean", action="store_true",
                        help="check formal pointers against the cached audit/latest.json")
    args = parser.parse_args(argv)
    try:
        ctx = run(args.root, args.run_counterexamples, args.family, args.lean)
    except (CheckError, ConfigError) as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1
    modes = [name for name, on in
             (("counterexamples", args.run_counterexamples), ("family", args.family), ("lean", args.lean)) if on]
    print(f"ok {len(ctx.entries)} entries, {len(INVARIANTS)} invariants"
          f"{', modes: ' + ', '.join(modes) if modes else ''} [{ctx.kind} repo]")
    for notice in ctx.notices:
        print(f"notice {notice}")
    return 0


if __name__ == "__main__":
    # Dispatch to the canonical module: under `python -m`, this file runs as `__main__`
    # and its classes would be distinct from the `mdept.check` ones that artifacts and
    # callers import, breaking isinstance checks.
    from mdept.check import main as _main

    raise SystemExit(_main())
