"""The family this package reads: both ledgers, the inbox, and the listed consumers.

`parse.load_entries` reads one repo and stays the primitive. This module answers
the question a command run from somewhere else asks instead: where is the
department, and what does it hold? It locates the public checkout from this
package's own file, so `python -m mdept.query` works from any directory in the
family; the private sibling through `config.private_root`; and the consumers
through the private repo's `repos.yaml`.

With no private repo on the machine, the public ledger alone is the family.
Every command still runs, over less: that is the one place a smaller answer is
right rather than a silent default, because a public checkout is a complete repo
and its ledger is the whole of what it knows.

Resolution is lazy, one side at a time. `locate` reads the anchor repo's own
directory and nothing else; the other ledger is resolved when something asks for
it, and `repos.yaml` is parsed when the consumers are first asked for. So a plain
`python -m mdept.check` in the public repo never touches the private side, and a
broken `MATHDEPT_PRIVATE` cannot fail a command that had no use for it.
"""

from __future__ import annotations

import fnmatch
import os
import re
import stat
from dataclasses import dataclass, field
from pathlib import Path

from . import CheckError, ConfigError
from . import anchors, config, parse

#: The generated-file marker, read from a file's opening lines. Derived rather
#: than listed: a generated file says so at the top, and the next one will too.
#: The marker has to OPEN a line once markup is stripped, not merely occur in
#: one, or a hand-written sentence about something "generated by hand" would
#: exempt its whole file from I21.
GENERATED_MARKERS = ("generated by", "role: generated")
GENERATED_HEAD_LINES = 8

#: What may sit in front of the marker: an HTML comment opener, then the heading,
#: bullet, quote and emphasis markup `mdept.anchors` already knows how to strip.
_COMMENT_OPEN_RE = re.compile(r"^\s*(?:<!--)?\s*")


def marker_line(line: str) -> str:
    """A line with its comment opener and markdown markup stripped, lower-cased.

    Reuses the anchor stripper, so "what opens a line" means the same thing here
    as it does when an anchor resolves.
    """
    return anchors.line_text(_COMMENT_OPEN_RE.sub("", line, count=1)).lower()


@dataclass(frozen=True)
class Consumer:
    """One repo listed in `repos.yaml`: where it is, what to skip, where its view goes."""

    name: str
    path: Path
    ignore: tuple[str, ...] = ()
    view: str = "docs/MATH.md"

    @property
    def view_path(self) -> Path:
        return self.path / self.view

    def ignored(self, rel: str) -> bool:
        """True when this repo-relative path matches one of the consumer's globs.

        Matched with `fnmatch` against the repo-relative path, where `*` crosses
        directory separators: `outputs/*` skips that whole tree, and `*.npz`
        skips those files wherever they sit.
        """
        return any(fnmatch.fnmatch(str(rel), pattern) for pattern in self.ignore)

    def files(self) -> list[Path]:
        """Every file this repo owns, sorted, as one scannable surface.

        Three prunings, and each is about ownership rather than noise:
        `parse.IGNORE_DIRS` is tool and build state; a nested checkout (any
        subdirectory carrying its own `.git`, which is what a git worktree or a
        submodule is) belongs to that other checkout, and an agent worktree
        appearing under `.claude/` would otherwise make a family check pass or
        fail depending on who happens to be working; and the `ignore` globs are
        the consumer's own declaration of what is not a citation surface.
        """
        found = []
        for directory, subdirectories, filenames in os.walk(self.path):
            here = Path(directory)
            subdirectories[:] = sorted(
                name for name in subdirectories
                if name not in parse.IGNORE_DIRS and not (here / name / ".git").exists()
            )
            for name in sorted(filenames):
                rel = (here / name).relative_to(self.path)
                if not self.ignored(str(rel)):
                    found.append(here / name)
        return found

    def rel(self, path: Path) -> str:
        return str(Path(path).relative_to(self.path))

    def text(self, path: Path) -> str | None:
        """The file's text, or None when it is not a readable text file at all.

        None means one definite thing: this path holds no prose to scan, either
        because it is not a regular file (a dangling symlink, a FIFO, a socket)
        or because its bytes are not UTF-8. Anything else, an unreadable regular
        file above all, is a `CheckError` naming the path: a permission problem
        silently reported as "no citations here" is the failure this whole lane
        exists to remove.
        """
        path = Path(path)
        try:
            if not path.stat().st_mode & stat.S_IFREG:
                return None
        except OSError:
            return None
        try:
            return path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            return None
        except OSError as exc:
            raise CheckError(
                f"I21 unlisted citation: {self.name}:{self.rel(path)}: field '<file>': "
                f"cannot be read ({exc.strerror}); it is a regular file in a listed "
                "consumer, so it is a citation surface and has to be readable"
            ) from exc

    def is_generated(self, path: Path, text: str | None = None) -> bool:
        """True when one of the file's opening lines declares it generated."""
        if text is None:
            text = self.text(path)
        if text is None:
            return False
        return any(
            marker_line(line).startswith(GENERATED_MARKERS)
            for line in text.splitlines()[:GENERATED_HEAD_LINES]
        )


@dataclass
class Repo:
    """One math repo: its root, its kind, and its two markdown surfaces."""

    root: Path
    kind: str
    _entries: list | None = field(default=None, repr=False)
    _requests: list | None = field(default=None, repr=False)

    @property
    def private(self) -> bool:
        return self.kind == "private"

    def entries(self) -> list:
        if self._entries is None:
            self._entries = parse.load_entries(self.root)
        return self._entries

    def requests(self) -> list:
        if self._requests is None:
            self._requests = parse.load_requests(self.root)
        return self._requests


#: The sentinel for "the other ledger has not been looked for yet". None is a
#: real answer (there is no copy on this machine), so it cannot stand for both.
_UNRESOLVED = object()


@dataclass
class Family:
    """Both ledgers and the consumers, as one read surface, resolved on demand."""

    anchor: Repo
    _other: object = field(default=_UNRESOLVED, repr=False)
    _consumers: dict | None = field(default=None, repr=False)

    @property
    def other(self) -> Repo | None:
        """The ledger this family was not located from, resolved on first ask."""
        if self._other is _UNRESOLVED:
            root = (
                config.public_root(self.anchor.root) if self.anchor.private
                else config.private_root(self.anchor.root)
            )
            kind = "public" if self.anchor.private else "private"
            self._other = None if root is None else Repo(root=root, kind=kind)
        return self._other

    @property
    def public(self) -> Repo | None:
        return self.anchor if not self.anchor.private else self.other

    @property
    def private(self) -> Repo | None:
        return self.anchor if self.anchor.private else self.other

    @property
    def repos_yaml(self) -> Path | None:
        """The consumer map, which lives in the private repo, or None."""
        private = self.private
        if private is None:
            return None
        candidate = private.root / "repos.yaml"
        return candidate if candidate.is_file() else None

    @property
    def consumers(self) -> dict:
        """Name to Consumer, parsed from `repos.yaml` on first ask."""
        if self._consumers is None:
            declared = self.repos_yaml
            self._consumers = {} if declared is None else read_consumers(declared)
        return self._consumers

    def ledgers(self) -> list[Repo]:
        return [repo for repo in (self.public, self.private) if repo is not None]

    def entries(self) -> list:
        """Every entry in the family, public first within an ID, sorted by ID."""
        return sorted((e for repo in self.ledgers() for e in repo.entries()), key=lambda e: e.id)

    def by_id(self) -> dict:
        return {entry.id: entry for entry in self.entries()}

    def requests(self) -> list:
        return self.private.requests() if self.private is not None else []

    def repo_at(self, root: Path) -> Repo:
        """The Repo object for this root, whichever side of the family it is.

        The anchor is tried first and returned without resolving anything else,
        because this is the call a plain single-repo command makes and it must
        not drag the other side of the family in behind it.
        """
        wanted = Path(root).resolve()
        if self.anchor.root == wanted:
            return self.anchor
        other = self.other
        if other is not None and other.root == wanted:
            return other
        return Repo(root=wanted, kind=config.repo_kind(wanted))

    def sibling_of(self, root: Path) -> Path | None:
        """The other ledger's root, seen from this one."""
        wanted = Path(root).resolve()
        if self.anchor.root != wanted:
            # Any root but the anchor was reached through the other ledger, so
            # the anchor is what sits beside it.
            return self.anchor.root
        other = self.other
        return None if other is None else other.root

    def consumer(self, name: str) -> Consumer:
        """One listed consumer, or a failure that names the ones there are."""
        consumers = self.consumers
        found = consumers.get(name)
        if found is None:
            if not consumers:
                raise ConfigError(
                    f"{name!r} cannot be resolved: there is no consumer list on this "
                    "machine. `repos.yaml` lives in the private repo, so a public "
                    f"checkout alone has no consumers. Set {config.PRIVATE_ENV}, or put "
                    f"a checkout at ../{config.PRIVATE_REPO_DIRNAME}."
                )
            raise ConfigError(
                f"{name!r} is not a consumer in {self.repos_yaml or 'repos.yaml'}; "
                f"the listed repos are {sorted(consumers)}"
            )
        return found


def locate(root: Path | str | None = None) -> Family:
    """The family, as paths only: nothing is read off disk yet.

    With `root`, that repo anchors the family and its sibling is resolved from
    it, which is what lets a test fixture pair be a family. Without one, the cwd
    is tried first, and then this package's own checkout, so a command run from
    a consumer repo finds the department it was installed from.
    """
    if root is None:
        try:
            anchor = config.find_repo_root()
        except ConfigError:
            anchor = config.package_root()
    else:
        anchor = Path(root).resolve()

    return Family(anchor=Repo(root=anchor, kind=config.repo_kind(anchor)))


def load_family(root: Path | str | None = None) -> Family:
    """`locate`, with both ledgers and the inbox read now rather than later.

    Reading eagerly is the point: a malformed entry in either repo is a parse
    failure at the start of the command, naming its file, and not a missing row
    in the middle of an answer.
    """
    family = locate(root)
    for repo in family.ledgers():
        repo.entries()
    family.requests()
    return family


def read_consumers(repos_yaml: Path) -> dict:
    """`repos.yaml` consumers as name to Consumer, paths resolved against the repo."""
    repos_yaml = Path(repos_yaml)
    declared = parse.load_repos_yaml(repos_yaml)
    root = repos_yaml.parent
    consumers = {}
    for name, value in declared["consumers"].items():
        raw = Path(str(value["path"])).expanduser()
        consumers[name] = Consumer(
            name=name,
            path=raw if raw.is_absolute() else (root / raw),
            ignore=tuple(value["ignore"]),
            view=value["view"],
        )
    return consumers


def require_private(family: Family, what: str) -> Repo:
    """The private repo, or a failure that says what needed it."""
    if family.private is None:
        raise ConfigError(
            f"{what} needs the private repo (the inbox and the consumer map live there). "
            f"Set {config.PRIVATE_ENV}, or put a checkout at ../{config.PRIVATE_REPO_DIRNAME}."
        )
    return family.private


def request_by_stem(family: Family, stem: str):
    """One request from the inbox, by its filename stem."""
    require_private(family, f"MDR:{stem}")
    for request in family.requests():
        if request.stem == stem:
            return request
    raise CheckError(
        f"I12 dangling: inbox/{stem}.md: field '<request>': "
        "names no request in inbox/ or inbox/done/"
    )
