"""The generated views: `ledger/INDEX.md` and `ledger.json`.

Run: `python -m mdept.index [--root PATH] [--check]`

`render()` builds both files in memory from the entries on disk. Writing is
`make regen`; `--check` regenerates in memory and fails on any drift, so a
hand-edit to a generated file is caught rather than silently kept. Nothing here
reads the previous output, so the views cannot accumulate stale rows.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path

from . import CheckError
from . import config, parse, schema

INDEX_PATH = "ledger/INDEX.md"
JSON_PATH = "ledger.json"
SCHEMA_VERSION = 1

HEADER = "<!-- Generated by `python -m mdept.index`. Do not edit. Run: make regen -->"

_ESTABLISHED = ("cited", "proven-formal", "proven-informal")
_IMPLIED_BY = ("below_of", "special_case_of")


def escape(text: str) -> str:
    """Make a value safe inside a markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def inheritance_notices(entries: list) -> list[str]:
    """I9b: unsettled entries that something already established implies."""
    by_id = {e.id: e for e in entries}
    notices = []
    for entry in entries:
        if entry.status not in schema.UNSETTLED_STATUSES:
            continue
        for relation in _IMPLIED_BY:
            for target in entry.front["between"][relation]:
                other = by_id.get(target)
                if other is not None and other.status in _ESTABLISHED:
                    notices.append(
                        f"I9b: {entry.id} is {entry.status} but {target} ({other.status}) implies it; "
                        "it may settle by inheritance"
                    )
    return notices


def partial_results(entries: list) -> list[tuple]:
    """Settled entries that are a special case of something still unsettled."""
    by_id = {e.id: e for e in entries}
    rows = []
    for entry in entries:
        if entry.status in schema.UNSETTLED_STATUSES:
            continue
        for target in entry.front["between"]["special_case_of"]:
            other = by_id.get(target)
            if other is not None and other.status in schema.UNSETTLED_STATUSES:
                rows.append((entry.id, entry.status, target, other.status))
    return rows


def _between_column(entry) -> str:
    parts = []
    for relation in schema.RELATIONS:
        targets = entry.front["between"][relation]
        if targets:
            parts.append(f"{relation} {' '.join(targets)}")
    return "; ".join(parts) or "."


def _status_summary(entries: list) -> list[str]:
    lines = ["## 1. Status summary", "", "| Status | Entries |", "|---|---|"]
    for status in schema.STATUSES:
        lines.append(f"| `{status}` | {sum(1 for e in entries if e.status == status)} |")
    lines += ["", "| Credit | Stipulated | Settled |", "|---|---|---|"]
    for who in schema.WHO:
        stipulated = sum(1 for e in entries if e.at("provenance.stipulated_by.who") == who)
        settled = sum(1 for e in entries if e.at("provenance.settled_by.who") == who)
        lines.append(f"| {who} | {stipulated} | {settled} |")
    return lines


def _topic_index(entries: list) -> list[str]:
    lines = ["## 2. Topic Index", "", "| Topic | Entries | Connects to | Key tags |", "|---|---|---|---|"]
    topics: dict[str, list] = {}
    for entry in entries:
        for topic in entry.front["topics"]:
            topics.setdefault(topic, []).append(entry)
    for topic in sorted(topics):
        members = topics[topic]
        neighbours = sorted({t for e in members for t in e.front["topics"] if t != topic})
        tags = sorted({e.front["source"] for e in members if e.front["source"]})
        lines.append(
            f"| {escape(topic)} | {' '.join(e.id for e in members)} | "
            f"{' '.join(neighbours) or '.'} | {' '.join(tags) or '.'} |"
        )
    return lines


def _all_entries(entries: list) -> list[str]:
    lines = [
        "## 3. All entries",
        "",
        "| ID | Title | Status | Kind | Raised by | Formal decl | Between |",
        "|---|---|---|---|---|---|---|",
    ]
    for entry in entries:
        lines.append(
            f"| {entry.id} | {escape(entry.title)} | `{entry.status}` | {entry.kind} "
            f"| {escape(entry.at('provenance.raised_by.repo') or '.')} "
            f"| {escape(entry.at('formal.decl') or '.')} | {escape(_between_column(entry))} |"
        )
    return lines


def _partial_section(entries: list) -> list[str]:
    lines = ["## 4. Partial results", "",
             "Settled entries that are a special case of something still open.", "",
             "| Settled entry | Status | Special case of | That entry |", "|---|---|---|---|"]
    for entry_id, status, target, target_status in partial_results(entries):
        lines.append(f"| {entry_id} | `{status}` | {target} | `{target_status}` |")
    return lines


def _by_consumer(entries: list) -> list[str]:
    lines = ["## 5. By consumer", "", "| Repo | Raised | Cited |", "|---|---|---|"]
    raised: dict[str, list] = {}
    cited: dict[str, list] = {}
    for entry in entries:
        repo = entry.at("provenance.raised_by.repo")
        if repo:
            raised.setdefault(repo, []).append(entry)
        for citation in entry.front["cited_by"]:
            match = schema.CITED_BY_RE.match(citation)
            if match:
                cited.setdefault(match.group("repo").strip(), []).append(entry)
    for repo in sorted(set(raised) | set(cited)):
        lines.append(
            f"| {escape(repo)} "
            f"| {' '.join(f'{e.id} ({e.status})' for e in raised.get(repo, [])) or '.'} "
            f"| {' '.join(f'{e.id} ({e.status})' for e in cited.get(repo, [])) or '.'} |"
        )
    return lines


def _requests(requests: list) -> list[str]:
    lines = ["## 6. Requests", "", "| Request | Filed | State | Ledger IDs |", "|---|---|---|---|"]
    for request in requests:
        ids = request.front.get("ledger_ids") or []
        lines.append(
            f"| MDR:{request.stem} | {escape((request.front.get('from') or {}).get('date', '.'))} "
            f"| `{escape(request.state)}` | {' '.join(ids) or '.'} |"
        )
    return lines


def _report(entries: list) -> list[str]:
    lines = ["## 7. Contradiction and staleness report", ""]
    notices = inheritance_notices(entries)
    if not notices:
        lines.append("No notices. `python -m mdept.check` passes with nothing to report.")
    else:
        lines.extend(f"- {notice}" for notice in notices)
    return lines


def render_index(entries: list, requests: list, kind: str) -> str:
    lines = [
        "# Ledger index",
        HEADER,
        "",
        f"{len(entries)} entries in the {kind} repo. Grep an ID to find its entry file.",
        "",
    ]
    for section in (
        _status_summary(entries),
        _topic_index(entries),
        _all_entries(entries),
        _partial_section(entries),
        _by_consumer(entries),
        _requests(requests),
        _report(entries),
    ):
        lines.extend(section)
        lines.append("")
    return "\n".join(lines).rstrip("\n") + "\n"


def render_json(entries: list, requests: list) -> str:
    digest = hashlib.sha256()
    for entry in entries:
        digest.update(entry.front_text.encode("utf-8"))
        digest.update(b"\0")
    payload = {
        "schema_version": SCHEMA_VERSION,
        "generated_from": digest.hexdigest(),
        "entries": [dict(entry.front, path=entry.rel) for entry in entries],
        "requests": [
            {
                "request": request.front.get("request"),
                "state": request.state,
                "from": request.front.get("from"),
                "priority": request.front.get("priority"),
                "ledger_ids": request.front.get("ledger_ids") or [],
                "candidates": request.candidates(),
                "path": request.rel,
            }
            for request in requests
        ],
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


def render(root: Path) -> dict[str, str]:
    """Both generated views, as {repo-relative path: content}."""
    root = Path(root).resolve()
    entries = parse.load_entries(root)
    requests = parse.load_requests(root)
    kind = config.repo_kind(root)
    return {
        INDEX_PATH: render_index(entries, requests, kind),
        JSON_PATH: render_json(entries, requests),
    }


def write(root: Path) -> list[str]:
    """Write both views. Returns the paths that changed."""
    root = Path(root).resolve()
    changed = []
    for rel, content in render(root).items():
        path = root / rel
        path.parent.mkdir(parents=True, exist_ok=True)
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            path.write_text(content, encoding="utf-8")
            changed.append(rel)
    return changed


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m mdept.index", description=__doc__.splitlines()[0])
    parser.add_argument("--root", default=None, help="repo root (default: nearest ancestor with ledger/)")
    parser.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    args = parser.parse_args(argv)
    root = config.find_repo_root(args.root) if args.root is None else Path(args.root).resolve()

    try:
        rendered = render(root)
    except CheckError as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1

    if not args.check:
        changed = write(root)
        print(f"ok wrote {len(rendered)} generated views" + (f", changed: {changed}" if changed else ", no change"))
        return 0

    stale = []
    for rel, content in rendered.items():
        path = root / rel
        if not path.is_file() or path.read_text(encoding="utf-8") != content:
            stale.append(rel)
    if stale:
        print(f"FAIL I16 generated: {stale}: field '<content>': stale; run `make regen`", file=sys.stderr)
        return 1
    print(f"ok {len(rendered)} generated views are fresh")
    return 0


if __name__ == "__main__":
    # Dispatch to the canonical module: under `python -m`, this file runs as `__main__`
    # and its classes would be distinct from the `mdept.index` ones that artifacts and
    # callers import, breaking isinstance checks.
    from mdept.index import main as _main

    raise SystemExit(_main())
