"""Generate a consumer's local view of the department: its `docs/MATH.md`.

Run:

    python -m mdept.view --consumer NAME --write
    python -m mdept.view --consumer NAME --check
    python -m mdept.view --consumer NAME --write --out /tmp/MATH.md

A consumer repo has no local view of what the department holds for it. Without
one, the question "what has the department said about this closure" is answered
by reading two ledgers in another repo, which is exactly the trip an author in
the middle of a change does not take. The view puts the answer in the repo that
needs it, as a generated file: `--write` rewrites it, `--check` fails on drift,
and nothing in it is typed by hand.

Three things go in, and nothing else: the entries this repo raised, every
citation of an entry from this repo with the line it sits on, and every `MDR:`
request token found in the repo with what it has become. The output is
deterministic, with no timestamp, so `--check` is a real guard rather than a
diff against the clock.

The written path is the consumer's `view` in `repos.yaml` (`docs/MATH.md` by
default). It is the one file in a consumer this package writes, it says so in
its own opening lines, and it is the one file I21 does not read back.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from . import CheckError, ConfigError
from . import anchors, parse, schema
from . import family as family_mod

HEADER_NOTE = "do not edit"


def header(consumer) -> list[str]:
    return [
        f"# Math department, {consumer.name}",
        f"<!-- Generated by `python -m mdept.view --consumer {consumer.name} --write`; "
        f"{HEADER_NOTE}. -->",
        "",
        "What the department holds for this repo. Cite an entry by its `MD_####` ID and",
        "carry its status word on the citing line. An `MDR:` token records an exposure and",
        "licenses nothing: no verdict, number or design decision may rest on one.",
        "",
    ]


def collect(family, consumer) -> dict:
    """Everything the view reports, as the JSON shape the markdown is built from."""
    entries = family.entries()
    raised = [e for e in entries if e.at("provenance.raised_by.repo") == consumer.name]
    citations = _citations(entries, consumer)
    cited_lines: dict[str, list[str]] = {}
    for citation in citations:
        cited_lines.setdefault(citation["id"], []).append(f"{citation['path']}:{citation['line']}")
    return {
        "consumer": consumer.name,
        "path": consumer.view,
        "raised": [_raised_record(entry, consumer, cited_lines) for entry in raised],
        "cited": citations,
        "requests": _request_tokens(family, consumer),
    }


def _anchor_state(entry, consumer) -> tuple[int | None, str]:
    """(line, condition) for this entry's anchor in the consumer's document.

    The condition is reported and not swallowed. An anchor that no longer
    resolves is precisely the silent breakage this view exists to end, so
    collapsing "resolved at line 22", "points nowhere" and "points at two
    places" to a missing line number would reproduce it in the one file a
    consumer actually reads.
    """
    anchor = entry.at("provenance.raised_by.anchor")
    doc = entry.at("provenance.raised_by.doc")
    if anchor is None or doc is None:
        return None, "unanchored"
    doc_path = consumer.path / doc
    if not doc_path.is_file():
        return None, "doc missing"
    text = consumer.text(doc_path)
    if text is None:
        return None, "doc is not a text file"
    found = anchors.matches(anchor, text)
    if not found:
        return None, "does not resolve"
    if len(found) > 1 and anchors.classify(anchor) in anchors.UNIQUE_FORMS:
        return found[0].line, "ambiguous at lines " + ", ".join(str(h.line) for h in found)
    return found[0].line, "resolved"


def _raised_record(entry, consumer, cited_lines: dict) -> dict:
    anchor = entry.at("provenance.raised_by.anchor")
    line, condition = _anchor_state(entry, consumer)
    return {
        "id": entry.id,
        "status": entry.status,
        "title": entry.title,
        "statement": " ".join(entry.sections().get("Statement", "").split()),
        "doc": entry.at("provenance.raised_by.doc"),
        "anchor": anchor,
        "anchor_form": anchors.classify(anchor) if anchor else None,
        "anchor_line": line,
        "anchor_condition": condition,
        "citation_words": list(schema.citation_words(entry.status)),
        "cited_at": sorted(cited_lines.get(entry.id, [])),
    }


def _citations(entries: list, consumer) -> list[dict]:
    found = []
    for entry in entries:
        for citation in entry.front.get("cited_by") or []:
            split = schema.split_cited_by(citation)
            if split is None or split[0] != consumer.name:
                continue
            _repo, rel, locator = split
            path = consumer.path / rel
            if not path.is_file():
                raise CheckError(
                    f"I15 citation: {entry.rel}: field 'cited_by': {path} does not exist; "
                    "run `python -m mdept.check --family` and fix the ledger first"
                )
            text = consumer.text(path)
            if text is None:
                raise CheckError(
                    f"I15 citation: {entry.rel}: field 'cited_by': {path} is not a text file"
                )
            for number, line in enumerate(text.splitlines(), start=1):
                if entry.id in line:
                    found.append({
                        "id": entry.id,
                        "status": entry.status,
                        "path": rel,
                        "line": number,
                        "locator": locator,
                        "citation_words": list(schema.citation_words(entry.status)),
                    })
    return sorted(found, key=lambda c: (c["path"], c["line"], c["id"]))


def _request_tokens(family, consumer) -> list[dict]:
    from .query import resolve as resolve_request

    view = consumer.view_path
    requests = {request.stem: request for request in family.requests()}
    seen: dict[str, list[str]] = {}
    for path in consumer.files():
        if path == view:
            continue
        text = consumer.text(path)
        if text is None or consumer.is_generated(path, text):
            continue
        rel = consumer.rel(path)
        for number, stem, candidate in parse.request_stem_tokens(text):
            token = f"MDR:{stem}" + (f"#{candidate}" if candidate else "")
            # Located here, where the token was read. Resolving it first and
            # letting the inbox raise would report a mistyped token as a missing
            # request file, sending the reader to the math repo to look for a
            # request that never existed instead of to the line that misspelt it.
            request = requests.get(stem)
            if request is None:
                raise CheckError(
                    f"I12 dangling: {consumer.name}:{rel}:{number}: field '<MDR token>': "
                    f"{token} names no request in inbox/ or inbox/done/"
                )
            if candidate and candidate not in request.candidates():
                raise CheckError(
                    f"I12 dangling: {consumer.name}:{rel}:{number}: field '<MDR token>': "
                    f"{token} names no '### {candidate}' heading in {request.rel}, "
                    f"which offers {request.candidates()}"
                )
            seen.setdefault(token, []).append(f"{rel}:{number}")
    records = []
    for token in sorted(seen):
        answer = resolve_request(family, token)
        records.append({
            "token": token,
            "state": answer["state"],
            "candidates": answer["candidates"],
            "found_at": sorted(seen[token]),
        })
    return records


def _raised_at(record: dict) -> str:
    """The one line that says where the entry was raised, and whether it still is."""
    condition = record["anchor_condition"]
    if condition == "unanchored":
        return "not recorded: the entry carries no document anchor."
    where = f"`{record['doc']}:{record['anchor_line']}`" if record["anchor_line"] else f"`{record['doc']}`"
    anchor = f"anchor `{record['anchor']}` ({record['anchor_form']})"
    if condition == "resolved":
        return f"{where}, {anchor}"
    return (
        f"{where}, {anchor}: **{condition}**. "
        "Either the anchor or the document moved; `python -m mdept.check --family` fails on it."
    )


def render(payload: dict, consumer) -> str:
    lines = header(consumer)

    lines += ["## Raised here", ""]
    if not payload["raised"]:
        lines += ["Nothing in this repo has raised a statement yet.", ""]
    for record in payload["raised"]:
        lines.append(f"### {record['id']} `{record['status']}` {record['title']}")
        lines.append("")
        lines.append("- **Raised at.** " + _raised_at(record))
        if record["citation_words"]:
            lines.append(
                "- **Cite with.** one of " + ", ".join(f"`{w}`" for w in record["citation_words"])
            )
        lines.append(
            "- **Cited at.** "
            + (", ".join(f"`{loc}`" for loc in record["cited_at"]) or "nowhere in this repo yet")
        )
        # The statement is last on purpose: it is one long line of LaTeX, and a
        # reader scanning this file is looking for the status and the places
        # first. Putting it above them pushes everything scannable off screen.
        if record["statement"]:
            lines.append(f"- **Statement.** {record['statement']}")
        lines.append("")

    lines += ["## Cited here", ""]
    if not payload["cited"]:
        lines += ["No file in this repo cites an entry.", ""]
    else:
        lines += ["| Entry | Status | Line | Cite with |", "|---|---|---|---|"]
        for citation in payload["cited"]:
            words = ", ".join(citation["citation_words"]) or "."
            lines.append(
                f"| {citation['id']} | `{citation['status']}` "
                f"| `{citation['path']}:{citation['line']}` | {words} |"
            )
        lines.append("")

    lines += ["## Request tokens", ""]
    if not payload["requests"]:
        lines += ["No `MDR:` token is open in this repo.", ""]
    for record in payload["requests"]:
        lines.append(f"### `{record['token']}` state `{record['state']}`")
        lines.append("")
        lines.append("Found at " + ", ".join(f"`{loc}`" for loc in record["found_at"]) + ".")
        lines.append("")
        lines += ["| Candidate | Became |", "|---|---|"]
        for candidate, outcome in sorted(record["candidates"].items()):
            if isinstance(outcome, str):
                became = outcome
            else:
                became = ", ".join(f"{item['id']} `{item['status']}`" for item in outcome)
            lines.append(f"| {candidate} | {became} |")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def generate(family, name: str) -> tuple[str, Path, dict]:
    """(rendered text, the default output path, the JSON payload) for one consumer."""
    consumer = family.consumer(name)
    payload = collect(family, consumer)
    return render(payload, consumer), consumer.view_path, payload


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python -m mdept.view", description=__doc__.splitlines()[0])
    parser.add_argument("--consumer", required=True, help="a consumer name from repos.yaml")
    parser.add_argument("--root", default=None, help="a math repo root (default: the installed checkout)")
    parser.add_argument("--write", action="store_true", help="write the view")
    parser.add_argument("--check", action="store_true", help="fail on any drift instead of writing")
    parser.add_argument("--out", default=None, help="write or check this path instead of the consumer's")
    parser.add_argument("--json", action="store_true", help="emit the machine view on stdout")
    args = parser.parse_args(argv)
    if args.write == args.check:
        parser.error("pass exactly one of --write and --check")

    try:
        family = family_mod.load_family(args.root)
        family_mod.require_private(family, "mdept.view")
        text, default_path, payload = generate(family, args.consumer)
    except (CheckError, ConfigError) as exc:
        print(f"FAIL {exc}", file=sys.stderr)
        return 1

    target = Path(args.out).expanduser() if args.out else default_path
    current = target.read_text(encoding="utf-8") if target.is_file() else None
    payload = dict(payload, target=str(target), fresh=current == text)

    if args.check:
        if args.json:
            print(json.dumps(payload, indent=2, sort_keys=True))
        if payload["fresh"]:
            if not args.json:
                print(f"ok {target} is fresh")
            return 0
        reason = "does not exist" if current is None else "drifted from the ledger"
        print(
            f"FAIL I16 generated: {target}: field '<content>': {reason}; "
            f"run `python -m mdept.view --consumer {args.consumer} --write`",
            file=sys.stderr,
        )
        return 1

    target.parent.mkdir(parents=True, exist_ok=True)
    if not payload["fresh"]:
        target.write_text(text, encoding="utf-8")
    if args.json:
        print(json.dumps(payload, indent=2, sort_keys=True))
        return 0
    changed = "no change" if payload["fresh"] else "written"
    print(
        f"ok {target} ({changed}): {len(payload['raised'])} raised, "
        f"{len(payload['cited'])} citations, {len(payload['requests'])} request tokens"
    )
    return 0


if __name__ == "__main__":
    # Dispatch to the canonical module: under `python -m`, this file runs as `__main__`
    # and its classes would be distinct from the `mdept.view` ones that artifacts and
    # callers import, breaking isinstance checks.
    from mdept.view import main as _main

    raise SystemExit(_main())
