#!/usr/bin/env python3
"""Generate the Lake root file that imports every module in a library.

    python scripts/gen_root.py --write            # rewrite MathDept.lean
    python scripts/gen_root.py --check            # exit 1 and print a diff on drift

From the private repo, which has no copy of this script:

    python ../math-dept/scripts/gen_root.py --lib MathDeptPrivate --write

The root is generated, never typed: a new entry file that nobody added an
import for would compile in isolation and be invisible to `lake build`, so the
axiom audit would never see it. Standard library only, so this runs before the
package is installed.

The header line records the exact command that regenerates THAT root, which is
not the same string in both repos: the private repo reaches across for this
script. It is derived from the path rather than hard-coded, so the two headers
cannot drift apart.
"""

from __future__ import annotations

import argparse
import difflib
import os
import sys
from pathlib import Path

DEFAULT_LIB = "MathDept"

HEADER_PREFIX = "-- Generated by scripts/gen_root.py. Do not edit. Run: "


def header(root: Path, name: str) -> str:
    """The header line, naming how to rerun this script from `root`."""
    script = Path(__file__).resolve()
    invocation = os.path.relpath(script, root)
    flag = "" if name == DEFAULT_LIB else f" --lib {name}"
    return f"{HEADER_PREFIX}python {invocation}{flag} --write"


def modules(library: Path, name: str) -> list[str]:
    """Every module in the library, as dotted names, sorted."""
    found = []
    for path in sorted(library.rglob("*.lean")):
        parts = path.relative_to(library).with_suffix("").parts
        found.append(".".join((name, *parts)))
    return sorted(found)


def render(root: Path, name: str) -> str:
    library = root / name
    lines = [header(root, name)] + [f"import {module}" for module in modules(library, name)]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="python scripts/gen_root.py", description=__doc__.splitlines()[0])
    parser.add_argument("--lib", default=DEFAULT_LIB, help=f"library name (default: {DEFAULT_LIB})")
    parser.add_argument("--root", default=None, help="repo root (default: the working directory)")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true", help="rewrite the root file")
    group.add_argument("--check", action="store_true", help="fail on drift")
    args = parser.parse_args(argv)

    root = Path(args.root).resolve() if args.root else Path.cwd().resolve()
    if not (root / args.lib).is_dir():
        print(f"FAIL {root / args.lib} does not exist. Run this from the repo root, "
              f"or pass --root; --lib names the library directory.", file=sys.stderr)
        return 1

    target = root / f"{args.lib}.lean"
    expected = render(root, args.lib)

    if args.write:
        changed = not target.is_file() or target.read_text(encoding="utf-8") != expected
        if changed:
            target.write_text(expected, encoding="utf-8")
        print(f"ok {target.name}: {len(expected.splitlines()) - 1} imports"
              f"{' (rewritten)' if changed else ' (no change)'}")
        return 0

    actual = target.read_text(encoding="utf-8") if target.is_file() else ""
    if actual == expected:
        print(f"ok {target.name} is fresh: {len(expected.splitlines()) - 1} imports")
        return 0
    diff = difflib.unified_diff(
        actual.splitlines(keepends=True), expected.splitlines(keepends=True),
        fromfile=f"{target.name} (on disk)", tofile=f"{target.name} (generated)",
    )
    print(f"FAIL {target.name} is stale; run: python scripts/gen_root.py --write --lib {args.lib}", file=sys.stderr)
    sys.stderr.writelines(diff)
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
